# AU template: https://github.com/majkinetor/au-packages-template

version: '{build}'
max_jobs: 1
image: WMF 5
# History plugin requires complete log
#clone_depth: 5
branches:
  only:
  - master
#build:
#  verbosity: minimal

environment:
  # Set au version to use or omit to use the latest. Specify branch name to use development version from Github
  au_version:
  au_push: false
  # Force test: use 1 to test all, or N to split testing into N groups
  au_test_groups: 1

  # Github token to commit pushed packages to repository
  github_user_repo: palethorper/chocolatey-packages
  github_api_key:
    secure: J6Q3aUEw6+1Su/KOme3vVSv0VQUl5dhUhbAdTd883dc8jwxUgDormi/1Yz96HhzCr5L4pejF/C1H6wl9RVG8N5mNV1p004nCVRCMq64GqvuglBIEGGie3nyJokCcai34HWM31FlPdZ+Y/U4dCvGyy1NN8vWLw6mWpIlcoG770S9OVAqQx8yaeaqKOBVPZbiFfgZOkwwfxlf3Xt3u0MBnyYUsAqtdeGPLgFOGqGYMgIdq2kp7IjgzVyFmxehAgokJieB00eVZAoGbJtEQpyO+X65vQVSndQ99b7RKXthrYq0HJTWWDuNy9HBt05OCwUxlVM41QHGsGvV3u+1AAu7ckiymCQiXtqyzE2NDOfF4ejKi/7STftvV2TUWj+YGWDSsL13RtlWWETcvNujUVJ/CbKLhS/07RhVtfUr9PALAW10y9AYAqG34XAoZkEVmixR1px0Vra3SY4U36B2M7ns82HCxxtSS2XTV6ASZKCU0q662vi+1o1L4FYI+zz9XTwrBVqWBvz90HpB1DDVHfBVi3pzUiBZSIpiChG08pvuIw/cWns5o6vB7SLZ8TuSIQ38ssa3HPSWZ4My4A64UIsla01KQ/BvjHRRFLOAXc/WK1ow8uwT19IH5nfDifnr90zlDhZsK1tytfD8FR5RmGTWI8eeyttqkA5d2jb6QdD+kbLGkps0Lr2CQuFcXqxDCWkxIqBJBNCAv/p3v+r5K/ouQneq9newCnGIs4H0wJ37ALIhqMKb8lL/Zug4WL8eMaL008y+WHFxfYAkNG90EqIy6A/BVELYHW/0Ufb8giz/SgA7giwQW/AgdP6muewTKoU49GPgC3WxO+Kz19QGyn5FBYmKxKuctYwha6LvYcMnFLhGyqEM1phlGcyK+aHpcZewxZi3pEZ0Us9CRJjPCcI+/9BXGByn2iu+E0mw1yTe6CAct1GLUELcC+Xx1bnyNlo3yRLSiftAEjqd3+M6KYPVvWFVPwAk4BPmaSOYoKt9rRgc=
 #https://ci.appveyor.com/tools/encrypt


  # Mail credentials - for error notifications
  mail_user:
    secure: YOUR_EMAIL_ACCOUNT_HERE_ENCRYPTED_STRING #https://ci.appveyor.com/tools/encrypt
  mail_pass:
    secure: YOUR_EMAIL_PASSWORD_HERE_ENCRYPTED_STRING #https://ci.appveyor.com/tools/encrypt
  mail_server: smtp.gmail.com
  mail_port: 587
  mail_enablessl: true

  # ID of the gist used to save run results - create a gist under the github_user (secret or not) and grab the id - https://gist.github.com/name/id
  # Optional, leave empty to create anonymous gist
  gist_id:

  # Force test: gist id for test results
  gist_id_test:

  # Chocolatey API key - to push updated packages
  api_key:
    secure: lwj+sFBfqXcPTIyVHyXdxIt2otWJcmnD9tmXrX/SZd/d+uVfH55aG61a50bQwd8a # https://ci.appveyor.com/tools/encrypt

init:
- git config --global user.email "chocolatey@realdimensions.net"
- git config --global user.name "Chocolatey"
- git config --global core.safecrlf false

install:
- ps: 'Get-CimInstance win32_operatingsystem -Property Caption, OSArchitecture, Version | fl Caption, OSArchitecture, Version'
- ps: $PSVersionTable
- git --version
- ps: |
    git clone -q https://github.com/majkinetor/au.git $Env:TEMP/au
    . "$Env:TEMP/au/scripts/Install-AU.ps1" $Env:au_version

- ps: |
    "Build info"
    '  {0,-20} {1}' -f 'SCHEDULED BUILD:', ($Env:APPVEYOR_SCHEDULED_BUILD -eq 'true')
    '  {0,-20} {1}' -f 'FORCED BUILD:'   , ($Env:APPVEYOR_FORCED_BUILD    -eq 'true')
    '  {0,-20} {1}' -f 'RE BUILD:'       , ($Env:APPVEYOR_RE_BUILD        -eq 'true')

build_script:
- ps: |
    $ErrorActionPreference = 'Continue'

    if ($Env:APPVEYOR_PROJECT_NAME  -like '*test*') { ./test_all.ps1 "random $Env:au_test_groups"; return }

    if ( ($Env:APPVEYOR_SCHEDULED_BUILD -ne 'true') -and ($Env:APPVEYOR_FORCED_BUILD -ne 'true') ) {
        switch -regex ($Env:APPVEYOR_REPO_COMMIT_MESSAGE)
        {
            '\[AU (.+?)\]'   { $forced = $Matches[1] }

            '\[PUSH (.+?)\]' {
                $packages = $Matches[1] -split ' '
                Write-Host "PUSHING PACKAGES: $packages"
                foreach ($package in $packages) {
                    Write-Host ("{0}`n{1}`n" -f ('-'*60), "PACKAGE: $package")
                    $package_dir = ls -recurse | ? { $_.Name -eq "$package.nuspec"} | select -First 1 | % Directory
                    if (!$package_dir) { Write-Warning "Can't find package '$package'"; continue }
                    pushd $package_dir; choco pack; Push-Package; popd
                }
                return
            }
        }
    }

    ./update_all.ps1 -ForcedPackages $forced
    7z a au_temp.zip $Env:TEMP\chocolatey\au\*

artifacts:
- path: update_info.xml
- path: Update-AUPackages.md
- path: au_temp.zip

notifications:
- provider: Email
  to: $(mail_user)
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true

#on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
